### ISSUE TITLE
On the acquisition of deleted data

### ISSUE THREAD

**Issue by luojianjava** [jcustenborder/kafka-connect-cdc-mssql#10]
Through your code, adding and deleting the data can be obtained, but the deleted data returns {'schema': null, "payload": null}, what's the problem?

**Comment by buinauskas** [comment]
The problem is the way Change Tracking behaves in SQL Server. This connector will return just the primary key with its' values and payload as a null on deletion.

**Comment by luojianjava** [comment]
那我需要怎么解决这个问题呢

**Comment by luojianjava** [comment]
So what do I need to do with this problem?

**Comment by buinauskas** [comment]
It's quite difficult to suggest something without knowing what you're doing exactly.

**Comment by luojianjava** [comment]
I want to increment the deleted data in the synchronous sqlserver to the Kafka

**Comment by jcustenborder** [comment]
@luojianjava This is not necessarily a problem with the connector. The connector is going to detect that there was a delete and push that to Kafka. Your use case is a little difference. Let's say for example that you are pushing changes from SQL Server to something downstream like Cassandra or Elasticsearch. When you remove the data from the SQL Server table you want to send that delete on to Cassandra or Elasticsearch. In Kafka a delete has the value and valueSchema as a null.
