### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by gorros** [jcustenborder/kafka-connect-cdc-mssql#9]
Following tests are failing:
```
Failed tests:
  MsSqlTableMetadataProviderTest » IllegalState Could not find docker-compose, l...
  QueryServiceTest » IllegalState Could not find docker-compose, looked in: Dock...
  BaseDocumentationTest.lambda$connectorRstTest$1:195 » NullPointer
```
I have installed Microsoft JDBC Driver 6.2. I tried with 6.0 version too.

**Comment by gorros** [comment]
By the way, there is jar in maven central
```
<dependency>
    <groupId>com.microsoft.sqlserver</groupId>
    <artifactId>mssql-jdbc</artifactId>
    <version>6.2.2.jre8</version>
</dependency>
```

**Comment by Wedjaa** [comment]
@gorros: do you have Docker installed? The latest version comes with docker-compose installed. It's used to manage the containers to execute the tests.

**Comment by gorros** [comment]
I installed Docket, however, I currently use Windows and I am not sure if I did everything correctly. I was able to build the project by turning of tests. Did not have much time to focus on docker.

**Comment by Wedjaa** [comment]
Try and do a ‘docker-compose up‘ in the folder where you checked out the source code, it should show Docker pulling the mssql image and start it up.

**Comment by jcustenborder** [comment]
@gorros This project is heavily dependant upon docker for the integration testing. Were you able to get things working? Unfortunately I haven't tested compiling on windows as I'm on Mac and Linux. You can also try disabling the tests.

**Comment by gorros** [comment]
@jcustenborder I've turned of tests for a while. When I have a time I will try with docker, and let you know. Anyway, the connector works.

**Comment by jcustenborder** [comment]
I'm going to go ahead and close this.
